esphome:
  name: "${device_name}"
  name_add_mac_suffix: false
  project:
    name: "${project_name}"
    version: "${project_version}"

esp32:
  board: esp32-evb
  # framework:
  #   type: esp-idf
  #   sdkconfig_options:
  #     CONFIG_ETH_RMII_CLK_OUTPUT : y
  #     LOG_LOCAL_LEVEL: ESP_LOG_DEBUG

preferences:
  flash_write_interval: 2min

api:

ota:

mdns:
  disabled: false

web_server:
  port: 80

debug:
  update_interval: 5s

# Logger must be at least debug (default)
logger:
  level: debug
  baud_rate: 0

ethernet:
  type: JL1101
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 0
  use_address: serverroom-node.stal

i2c:
  sda: GPIO5
  scl: GPIO4
  scan: true

uart:
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 9600

sn74hc165:
  - id: sn74hc165_hub
    clock_pin: GPIO16
    data_pin: GPIO17
    load_pin: GPIO4
    clock_inhibit_pin: GPIO18
    sr_count: 2

# Individual inputs
binary_sensor:
  - platform: gpio
    name: "SN74HC165 Pin #0"
    pin:
      sn74hc165: sn74hc165_hub
      # Use pin number 0
      number: 0
      inverted: false
sn74hc595:
  - id: 'sn74hc595_hub'
    data_pin: D5
    clock_pin: D8
    latch_pin: D7
    oe_pin: D6
    sr_count: 2

# Individual outputs
switch:
  - platform: gpio
    name: "SN74HC595 Pin #0"
    pin:
      sn74hc595: sn74hc595_hub
      # Use pin number 0
      number: 0
      inverted: false


sensor:

    
button:

  - platform: output
    name: "${friendly_name} Gate Close"
    output: relay2
    duration: 500ms
  - platform: output
    name: "${friendly_name} Gate Open"
    output: relay3
    duration: 500ms


switch:
  - platform: gpio
    name: "${friendly_name} Garage Heating"
    pin: GPIO12
    id: relay4
    restore_mode: ${relay_restore_mode}

output:
  - platform: gpio
    pin: GPIO16
    id: relay1
  - platform: gpio
    pin: GPIO2
    id: relay2
  - platform: gpio
    pin: GPIO32
    id: relay3

